apiVersion: v1
kind: Namespace
metadata:
  name: manual

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: manual
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      volumes:
      - name: static-files
        emptyDir:
          sizeLimit: 20Mi
      initContainers:
      - name: copy-static-files
        image: gcr.io/cloud-builders/gcloud
        command:
        - "bash"
        - "-c"
        - "gsutil cp -R $(SOURCE)/* /mnt/"
        env:
        - name: SOURCE
          value: gs://website-operator/public
        volumeMounts:
        - mountPath: /mnt
          name: static-files
          readOnly: false
      containers:
      - name: website
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: static-files
          readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: manual
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: website
  namespace: manual
spec:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
