# permissions for end users to view statics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: static-viewer-role
rules:
- apiGroups:
  - website.example.com
  resources:
  - statics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - website.example.com
  resources:
  - statics/status
  verbs:
  - get
