steps:
- id: test
  waitFor:
  - '-'
  name: 'eu.gcr.io/$PROJECT_ID/kubebuilder-tests'
  entrypoint: bash
  args:
  - '-c'
  - "go mod download && ginkgo -v ./controllers"
  dir: operator

- id: build
  waitFor:
  - '-'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'eu.gcr.io/$PROJECT_ID/operator:$BUILD_ID'
  - 'operator'

- id: push
  waitFor:
  - 'build'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/operator:$BUILD_ID'

- id: config
  waitFor:
  - '-'
  name: 'eu.gcr.io/$PROJECT_ID/kustomize'
  args:
  - 'edit'
  - 'set'
  - 'image'
  - 'controller=eu.gcr.io/$PROJECT_ID/operator:$BUILD_ID'
  dir: operator/config/manager

- id: config-build
  waitFor:
  - 'config'
  name: 'eu.gcr.io/$PROJECT_ID/kustomize'
  args:
  - 'build'
  - 'config/default'
  - '-o'
  - '/mnt/deploy.yaml'
  dir: operator
  volumes:
  - name: 'mnt'
    path: '/mnt'

- id: deploy
  waitFor:
  - 'config-build'
  - 'push'
  - 'test'
  name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'apply'
  - '--cluster=${_CLUSTER}'
  - '--location=${_LOCATION}'
  - '--filename=/mnt/deploy.yaml'
  volumes:
  - name: 'mnt'
    path: '/mnt'
